### ISSUE TITLE
CORS error when attempting to run locally

### ISSUE THREAD

**Issue by dtylam** [johnwalley/d3-tube-map#29]
When I tried to run an HTML page with a copy of the example json data, it refuses to load in the browser because of enhanced CORS security.

Firefox 68:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at .../pub.json. (Reason: CORS request not http).
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

Chrome 76:
Fetch API cannot load .../pub.json. URL scheme must be "http" or "https" for CORS request.

**Comment by johnwalley** [comment]
Hi @dtylam. Browsers won't let you read files from the local filesystem like this anymore.

I find it easiest to start up a small web server to serve the files. For example, I use [http-server](https://github.com/http-party/http-server) for running one off examples like this.

Another way around this would be to include the data in the js file itself. You can copy and paste the json structure and assign it to a variable and use that rather than loading from a file.

**Comment by dtylam** [comment]
Amazed by the quick reply! Yes I can work around this, thanks!!!
